### ISSUE TITLE
Pasting in normal mode breaks

### ISSUE THREAD

**Issue by BerkeleyTrue** [jeffreytse/zsh-vi-mode#5]
Not sure exactly when this started happening, but pasting breaks in subtle ways.

![image](https://user-images.githubusercontent.com/6775919/104135013-2b0ab100-5342-11eb-8726-6632857103a7.png)

Here I've entered normal mode, and hit `p`. This pasted the contents of the buffer below my prompt. I cannot navigate to this content, and hitting `dd` to delete the line only deleted a single character at the end of that pasted contented. 

If I type content in insert mode and then delete the line, my inserted content is deleted and the content that was pasted moves up into the correct position and is delete-able.

This is on the latest content but is reproduce-able a couple of commits back to `feat: provide a mechanism to execute extra commands`

**Comment by jeffreytse** [comment]
Hi @BerkeleyTrue 

Thanks for your actively reporting. And now I have confirm the bug about `dd` to delete the line but only deleted a single character at the end of content. But the navigation issue has not appeared yet. I will focus to figure out the issues and thanks agian for your support.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @BerkeleyTrue 

Thanks for your patient, and after some effort I have figured out some issues about visual line, such as `dd` to delete one line or `cc` to change one line and so on,  the commit ( 0bcfe76 ) has fixed the issues mentioned, welcome to update it.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @BerkeleyTrue 

So many thanks for your details about the issue, and my site still can not reproduce the issue. Could we have another approach for digging this issue?

Thanks and regards

**Comment by BerkeleyTrue** [comment]
@jeffreytse how do you mean? I can do some more debugging if you give me some guidance as I'm not that familiar with the inner works of zsh.

**Comment by jeffreytse** [comment]
@BerkeleyTrue

I means that if you could provide the details about your enviroment, such as plugins that you are using and so on, maybe it is a conflict on some plugin. Or that we can talk with one IM, maybe it is better.  : )

Thanks and regards

**Comment by BerkeleyTrue** [comment]
@jeffreytse Here are the plugins and config I use for zsh https://github.com/berkeleytrue/dotfiles/blob/master/.config/zsh/.zshrc
And my theme 
https://github.com/berkeleytrue/dotfiles/blob/master/.config/zsh/ghanima.zsh-theme

**Comment by jeffreytse** [comment]
Hi @BerkeleyTrue 

Thanks for your instructions to help me to check this issue, now your issue about weird paste has been addressed, this issue caused by your `.zshrc` at [L102](https://github.com/BerkeleyTrue/dotfiles/blob/1887e9185b0c942d557eda428dc2bf72e83c8b32/.config/zsh/.zshrc#L102), here you put your content to the `CUTBUFFER`, so you hit `p` will put the content after the current line.

Thanks and regards

**Comment by BerkeleyTrue** [comment]
@jeffreytse Thanks for looking into it. Should I remove the offending code?

**Comment by jeffreytse** [comment]
Hi @BerkeleyTrue 

Remove the offending code can fix your issue, actually I have reproduced your issue in my side with your dotfile, I have commit a [PR](https://github.com/BerkeleyTrue/dotfiles/pull/5) for you, you can have a try.

Thanks and regards

**Comment by BerkeleyTrue** [comment]
@jeffreytse I just gave it a try and I was still seeing the same behavior

**Comment by jeffreytse** [comment]
Hi @BerkeleyTrue 

I want to know whether you are using the terminal by remote ssh?

Thanks and regards

**Comment by BerkeleyTrue** [comment]
I use kitty terminal and run tmux

**Comment by jeffreytse** [comment]
Hi @BerkeleyTrue 

I have tried again your issue, it is a feature in fact, because you use `dd` to delete one line, you use `p` will put the line after current line and the paste content will be highlighted also.

Thanks and regards

**Comment by weisbrja** [comment]
@jeffreytse I think that the red highlighting caused the confusion. In my opinion red is not really a good color, because we associate it with errors.

**Comment by jeffreytse** [comment]
Hi @weisbrja, thanks for the suggestion, I will take a consideration for a better highlight background color by default.

**Comment by gregorriegler** [comment]
also something maybe related:
when I'm i normal mode, and I paste using ctrl+shift+v it filters all "g" characters from the string I pasted.
And if it contained a double "gg" it would only leave one "g"

**Comment by jeffreytse** [comment]
Hi @gregorriegler 

The issue you mentioned, I can not reproduce in my environment, could you tell me more details about it?

Thanks and Regards

**Comment by gregorriegler** [comment]
Ubuntu 20.04.2 LTS x86_64 with i3
Kernel: 5.4.0-81-generic
Shell: zsh 5.8 (x86_64-ubuntu-linux-gnu)
Terminal: x-terminal-emul

Reproducable with a zshrc with just zsh-vi-mode installed

**Comment by gregorriegler** [comment]
I should add: happens in alacritty as well as in gnome-terminal

**Comment by jeffreytse** [comment]
@gregorriegler  Thanks for your useful information.

**Comment by gregorriegler** [comment]
I am now on an ArcoLinux Distribution
Kernel: 5.13.12-arch1-1
Shell: zsh 5.8
Terminal: alacritty
and I am able to reproduce this Issue I had on Ubuntu with the filtered out g's

**Comment by jeffreytse** [comment]
@gregorriegler Than you! I will reply here if I get progress on it.

**Comment by BerkeleyTrue** [comment]
Hello, I've switched back to zsh-vim-mode now for a couple of months and I haven't noticed and issues with pasting. 

Don't know if others are having issues still that require this issue to remain open?

**Comment by jeffreytse** [comment]
@kiyoon Could you share more info by running `zvm_system_report` command? Thanks!

**Comment by kiyoon** [comment]
```
- Terminal program: tmux 3.5a (wezterm)
- Operating system: macOS 15.6 (24G84)
- ZSH framework: oh-my-zsh master (7366322), starship 1.20.1
- ZSH version: zsh 5.9 (arm64-apple-darwin24.0)
- ZVM version: zsh-vi-mode 0.11.0 (52480c2, 2025-08-19 16:59:08 +0900)
```

It's the same with no tmux settings. I'm using wezterm with terminfo wezterm (this is enabled opt-in, default is xterm-256color)
